### PR TITLE
Adding total number of AffixTiers in parentheses

### PR DESCRIPTION
**Pull request by TheOnlyBryan**
Setting ShowAffixBracketTierTotal=1 will enable display of the maximum
number of AffixTiers for a given Affix.

Off:
"+Armor.... T4 P"

On:
"+Armor.... T4(8) P"

I find this functionality useful in knowing just how good (or bad) an
item's tier is.

This uses the ShowAffixBracketTierTotal variable in Settings.ini.  I
have wired up the logic in the UI, but do not have a UI editor to add a
checkbox to the options dialog.  When ShowAffixBracketTier, a control
named ShowAffixBracketTierTotal will hide as you would expect.  All that
needs to be added is the actual visual control to the form.

### CODE REVIEW

**Comment by andreberg** [comment]
Hey TheFrequency, thanks for the pull request. I am about to release v1.8.2 soon which code-wise has lots of stuff rewritten and moved around (mainly to get rid of the "everything's global" issue that keeps creeping up more and more).

I probably won't be able to fit this in for the that release but I'll look into adding it to one of the next versions. 
By the way, the format that you have chosen "(N)" is already used for displaying the associated item level that a tier covers (it's an option that can be enabled in settings). Not sure yet how I will fit it in but I'll think of something.

**Comment by TheOnlyBryan** [comment]
Nice! Thanks for your time - I will wait for the new release and see about
tossing it in there then.  By the way, what app did you use to create the
UI? I saw a few on Google, but I was curious which one you used
specifically.

**Comment by andreberg** [comment]
For the initial test version I was doing the UI manually, for the first release with UI I used SmartGUI Creator.ahk which comes with SciTE4AutoHotkey and now I am using a slightly modified GUI Creator.ahk as a replacement for SmartGUI Creator.ahk.

**Comment by andreberg** [comment]
Changes added to v1.8.1. Thank you!

**Pull request closed without merging**
